name: RSS Feed Monitoring

on:
  schedule:
    # Esegui ogni 5 minuti
    - cron: '*/5 * * * *'
  workflow_dispatch: # Permette esecuzione manuale

jobs:
  poll-feeds:
    runs-on: ubuntu-latest

    steps:
      - name: Poll RSS Feeds
        run: |
          echo "🔄 Polling RSS feeds at $(date)"
          response=$(curl -s -w "%{http_code}" -X POST https://autogeorge.vercel.app/api/cron/poll-feeds)

          http_code="${response: -3}"
          body="${response%???}"

          if [ "$http_code" = "200" ]; then
            echo "✅ RSS polling successful"
            echo "$body" | jq '.'
          else
            echo "❌ RSS polling failed with status: $http_code"
            echo "$body"
            exit 1
          fi

      - name: Notify on failure
        if: failure()
        run: |
          echo "🚨 RSS monitoring failed - check the logs"